Repository SSAFY11-BUK0310/enjoy-trip, pull requests merged in 2024-05, with the labels that each got.

#11 [#7] pull-request template 적용 버그 수정
  .github/pull_request_template.md
Labels: bug

#6 [#4] 회원 도메인 개발 및 테스트
  .idea/checkstyle-idea.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/compiler.xml
  .idea/modules.xml
  .idea/modules/enjoytrip.main.iml
  .idea/modules/enjoytrip.test.iml
  .idea/uiDesigner.xml
  HELP.md
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  src/main/java/enjoytrip/EnjoytripApplication.java
  src/main/java/enjoytrip/global/BaseEntity.java
  src/main/java/enjoytrip/member/controller/MemberController.java
  src/main/java/enjoytrip/member/domain/Gender.java
  src/main/java/enjoytrip/member/domain/Member.java
  src/main/java/enjoytrip/member/domain/RoleType.java
  src/main/java/enjoytrip/member/dto/request/MemberSaveRequest.java
  src/main/java/enjoytrip/member/dto/request/MemberUpdateRequest.java
  src/main/java/enjoytrip/member/dto/response/MemberFindResponse.java
  src/main/java/enjoytrip/member/dto/response/MemberSaveResponse.java
  src/main/java/enjoytrip/member/dto/response/MemberUpdateResponse.java
  src/main/java/enjoytrip/member/exception/MemberNotFoundException.java
  src/main/java/enjoytrip/member/repository/MemberRepository.java
  src/main/java/enjoytrip/member/service/MemberService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/config/mybatis-config.xml
  src/main/resources/mapper/member-query.xml
  src/test/java/enjoytrip/EnjoytripApplicationTests.java
  src/test/java/enjoytrip/member/controller/MemberControllerTest.java
  src/test/java/enjoytrip/member/mock/MockMember.java
  src/test/java/enjoytrip/member/service/MemberServiceTest.java
Labels: enhancement

#10 [#5] 게시물 crud 구현
  .idea/.name
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/modules.xml
  build.gradle
  src/main/java/enjoytrip/article/controller/ArticleController.java
  src/main/java/enjoytrip/article/domain/Article.java
  src/main/java/enjoytrip/article/domain/ArticleType.java
  src/main/java/enjoytrip/article/dto/Base64Image.java
  src/main/java/enjoytrip/article/dto/request/ArticleSaveRequest.java
  src/main/java/enjoytrip/article/dto/request/ArticleUpdateRequest.java
  src/main/java/enjoytrip/article/dto/response/ArticleFindResponse.java
  src/main/java/enjoytrip/article/dto/response/ArticleSaveResponse.java
  src/main/java/enjoytrip/article/dto/response/ArticleUpdateResponse.java
  src/main/java/enjoytrip/article/exception/ArticleNotFoundException.java
  src/main/java/enjoytrip/article/repository/ArticleRepository.java
  src/main/java/enjoytrip/article/service/ArticleService.java
  src/main/java/enjoytrip/article/util/file/FileStore.java
  src/main/java/enjoytrip/article/util/file/UploadFile.java
  src/main/java/enjoytrip/global/exception/ErrorCode.java
  src/main/java/enjoytrip/member/controller/MemberController.java
  src/main/java/enjoytrip/member/dto/request/MemberUpdateRequest.java
  src/main/resources/application.yml
  src/main/resources/mapper/article-query.xml
  src/test/java/enjoytrip/article/controller/ArticleControllerTest.java
  src/test/java/enjoytrip/article/service/ArticleServiceTest.java
  src/test/resources/images/test.png
Labels: enhancement

#20 [#19] 파일스토어 이미지 파일 저장 버그 수정
  src/main/java/enjoytrip/article/controller/ArticleController.java
  src/main/java/enjoytrip/article/util/file/FileStore.java
  src/main/resources/config/mybatis-config.xml
Labels: bug

#18 [#17] 비밀번호 변경 기능 추가
  .idea/modules/enjoytrip.main.iml
  .idea/modules/enjoytrip.test.iml
  src/main/java/enjoytrip/global/exception/ErrorCode.java
  src/main/java/enjoytrip/member/controller/AuthController.java
  src/main/java/enjoytrip/member/controller/MemberController.java
  src/main/java/enjoytrip/member/domain/Member.java
  src/main/java/enjoytrip/member/dto/request/MemberPasswordUpdateRequest.java
  src/main/java/enjoytrip/member/dto/request/MemberUpdateRequest.java
  src/main/java/enjoytrip/member/dto/response/MemberLoginResponse.java
  src/main/java/enjoytrip/member/exception/IncorrectPasswordException.java
  src/main/java/enjoytrip/member/service/MemberService.java
  src/test/java/enjoytrip/member/controller/AuthControllerTest.java
  src/test/java/enjoytrip/member/controller/MemberControllerTest.java
  src/test/java/enjoytrip/member/mock/MockMember.java
  src/test/java/enjoytrip/member/service/MemberServiceTest.java
Labels: enhancement

#29 [#23] 게시물 다중 이미지 등록
  src/main/java/enjoytrip/article/controller/ArticleController.java
  src/main/java/enjoytrip/article/domain/Article.java
  src/main/java/enjoytrip/article/dto/request/ArticleSaveRequest.java
  src/main/java/enjoytrip/article/dto/request/ArticleUpdateRequest.java
  src/main/java/enjoytrip/article/dto/response/ArticleFindResponse.java
  src/main/java/enjoytrip/article/dto/response/ArticleSaveResponse.java
  src/main/java/enjoytrip/article/dto/response/ArticleUpdateResponse.java
  src/main/java/enjoytrip/article/exception/ArticleNotFoundException.java
  src/main/java/enjoytrip/article/exception/ArticleSaveFailedException.java
  src/main/java/enjoytrip/article/exception/ArticleUpdateFailedException.java
  src/main/java/enjoytrip/article/repository/ArticleRepository.java
  src/main/java/enjoytrip/article/service/ArticleService.java
  src/main/java/enjoytrip/article/util/file/FileStore.java
  src/main/java/enjoytrip/global/config/AuthConfig.java
  src/main/java/enjoytrip/global/constant/SessionConstant.java
  src/main/java/enjoytrip/global/domain/BaseEntity.java
  src/main/java/enjoytrip/global/exception/AuthException.java
  src/main/java/enjoytrip/global/exception/BusinessException.java
  src/main/java/enjoytrip/global/exception/ErrorCode.java
  src/main/java/enjoytrip/global/exception/ErrorResponse.java
  src/main/java/enjoytrip/global/exception/GlobalExceptionAdvice.java
  src/main/java/enjoytrip/global/filter/LoginCheckFilter.java
  src/main/java/enjoytrip/global/image/FileStore.java
  src/main/java/enjoytrip/global/image/Service/ImageService.java
  src/main/java/enjoytrip/global/image/UploadFile.java
  src/main/java/enjoytrip/global/image/controller/ImageController.java
  src/main/java/enjoytrip/global/image/domain/Image.java
  src/main/java/enjoytrip/global/image/dto/request/Base64Image.java
  src/main/java/enjoytrip/global/image/dto/request/ImageSave2ImageStorageRequestDto.java
  src/main/java/enjoytrip/global/image/dto/response/ImageSaveResponseDto.java
  src/main/java/enjoytrip/global/image/repository/ImageRepository.java
  src/main/resources/application.yml
  src/main/resources/config/mybatis-config.xml
  src/main/resources/mapper/article-query.xml
  src/main/resources/mapper/image-query.xml
  src/main/resources/static/images/no_image.png
  src/test/java/enjoytrip/article/controller/ArticleControllerTest.java
  src/test/java/enjoytrip/article/service/ArticleServiceTest.java
Labels: enhancement

#26 [#16] 댓글 기능 추가
  .idea/.name
  src/main/java/enjoytrip/comment/controller/CommentController.java
  src/main/java/enjoytrip/comment/domain/Comment.java
  src/main/java/enjoytrip/comment/dto/request/CommentSaveRequest.java
  src/main/java/enjoytrip/comment/dto/request/CommentUpdateRequest.java
  src/main/java/enjoytrip/comment/dto/response/CommentFindResponse.java
  src/main/java/enjoytrip/comment/dto/response/CommentSaveResponse.java
  src/main/java/enjoytrip/comment/dto/response/CommentUpdateResponse.java
  src/main/java/enjoytrip/comment/exception/CommentNotFoundException.java
  src/main/java/enjoytrip/comment/repository/CommentRepository.java
  src/main/java/enjoytrip/comment/service/CommentService.java
  src/main/java/enjoytrip/global/exception/ErrorCode.java
  src/main/java/enjoytrip/member/dto/request/MemberSaveRequest.java
  src/main/java/enjoytrip/member/service/MemberService.java
  src/main/resources/application.yml
  src/main/resources/config/mybatis-config.xml
  src/main/resources/mapper/comment-query.xml
  src/test/java/enjoytrip/comment/controller/CommentControllerTest.java
  src/test/java/enjoytrip/comment/mock/MockComment.java
  src/test/java/enjoytrip/comment/service/CommentServiceTest.java
  src/test/java/enjoytrip/member/controller/MemberControllerTest.java
  src/test/java/enjoytrip/member/mock/MockMember.java
  src/test/java/enjoytrip/member/service/MemberServiceTest.java
Labels: enhancement

#31 [#30] 게시물 조회수 증가 기능 추가
  src/main/java/enjoytrip/article/controller/ArticleController.java
  src/main/java/enjoytrip/article/dto/request/ArticleSaveRequest.java
  src/main/java/enjoytrip/article/dto/response/ArticleFindResponse.java
  src/main/java/enjoytrip/article/repository/ArticleRepository.java
  src/main/java/enjoytrip/article/service/ArticleService.java
  src/main/java/enjoytrip/global/exception/ErrorCode.java
  src/main/java/enjoytrip/global/image/controller/ImageController.java
  src/main/java/enjoytrip/global/image/dto/request/ImageSave2ImageStorageRequest.java
  src/main/java/enjoytrip/global/image/service/ImageService.java
  src/main/resources/mapper/article-query.xml
  src/test/java/enjoytrip/article/service/ArticleServiceTest.java
Labels: enhancement

#33 [#28] 메시지 기능 추가
  src/main/java/enjoytrip/global/config/AuthConfig.java
  src/main/java/enjoytrip/global/exception/ErrorCode.java
  src/main/java/enjoytrip/message/controller/MessageController.java
  src/main/java/enjoytrip/message/controller/MessageRoomController.java
  src/main/java/enjoytrip/message/domain/Message.java
  src/main/java/enjoytrip/message/domain/MessageRoom.java
  src/main/java/enjoytrip/message/dto/request/MessageRoomSaveRequest.java
  src/main/java/enjoytrip/message/dto/request/MessageRoomUpdateRequest.java
  src/main/java/enjoytrip/message/dto/request/MessageSaveRequest.java
  src/main/java/enjoytrip/message/dto/request/MessageUpdateRequest.java
  src/main/java/enjoytrip/message/dto/response/MessageFindResponse.java
  src/main/java/enjoytrip/message/dto/response/MessageRoomFindResponse.java
  src/main/java/enjoytrip/message/dto/response/MessageRoomSaveResponse.java
  src/main/java/enjoytrip/message/dto/response/MessageRoomUpdateResponse.java
  src/main/java/enjoytrip/message/dto/response/MessageSaveResponse.java
  src/main/java/enjoytrip/message/dto/response/MessageUpdateResponse.java
  src/main/java/enjoytrip/message/exception/MessageNotFoundException.java
  src/main/java/enjoytrip/message/repository/MessageRepository.java
  src/main/java/enjoytrip/message/repository/MessageRoomRepository.java
  src/main/java/enjoytrip/message/service/MessageRoomService.java
  src/main/java/enjoytrip/message/service/MessageService.java
  src/main/resources/config/mybatis-config.xml
  src/main/resources/mapper/message-query.xml
  src/main/resources/mapper/message-room-query.xml
  src/main/resources/mysql/data.sql
  src/main/resources/mysql/schema.sql
  src/test/java/enjoytrip/message/controller/MessageControllerTest.java
  src/test/java/enjoytrip/message/controller/MessageRoomControllerTest.java
  src/test/java/enjoytrip/message/mock/MockMessage.java
  src/test/java/enjoytrip/message/service/MessageRoomServiceTest.java
  src/test/java/enjoytrip/message/service/MessageServiceTest.java
Labels: enhancement

#37 [#35] 댓글 정렬 순서 변경
  src/main/java/enjoytrip/comment/controller/CommentController.java
  src/main/java/enjoytrip/comment/domain/Comment.java
  src/main/java/enjoytrip/comment/repository/CommentRepository.java
  src/main/java/enjoytrip/comment/service/CommentService.java
  src/main/resources/mapper/comment-query.xml
  src/main/resources/mysql/schema.sql
  src/test/java/enjoytrip/comment/service/CommentServiceTest.java
Labels: bug

#45 [#42] spring rest docs를 활용한 문서화
  build.gradle
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/list.adoc
  src/main/java/enjoytrip/global/filter/LoginCheckFilter.java
  src/main/resources/static/docs/index.html
  src/test/java/enjoytrip/article/controller/ArticleControllerRestDocsTest.java
  src/test/java/enjoytrip/article/service/ArticleServiceTest.java
  src/test/java/enjoytrip/comment/controller/CommentControllerRestDocsTest.java
  src/test/java/enjoytrip/config/AbstractRestDocsTest.java
  src/test/java/enjoytrip/config/RestDocsConfiguration.java
  src/test/java/enjoytrip/like/controller/LikeControllerRestDocsTest.java
  src/test/java/enjoytrip/member/controller/AuthControllerRestDocsTest.java
  src/test/java/enjoytrip/member/controller/MemberControllerRestDocsTest.java
  src/test/java/enjoytrip/message/controller/MessageControllerRestDocsTest.java
  src/test/java/enjoytrip/message/controller/MessageRoomControllerRestDocsTest.java
Labels: documentation

#46 [#44] 웹 계층에 필요한 필드를 dto에 추가
  src/main/java/enjoytrip/message/dto/response/MessageFindResponse.java
  src/main/java/enjoytrip/message/dto/response/MessageRoomFindResponse.java
  src/main/java/enjoytrip/message/service/MessageRoomService.java
  src/main/resources/mysql/schema.sql
  src/test/java/enjoytrip/message/service/MessageRoomServiceTest.java
Labels: bug

#48 [#47] 회원 비밀번호 암호화 기능
  build.gradle
  src/main/java/enjoytrip/global/config/SecurityConfig.java
  src/main/java/enjoytrip/global/service/OneWayCipherService.java
  src/main/java/enjoytrip/member/controller/AuthController.java
  src/main/java/enjoytrip/member/service/MemberService.java
  src/test/java/enjoytrip/article/service/ArticleServiceTest.java
  src/test/java/enjoytrip/member/controller/AuthControllerRestDocsTest.java
  src/test/java/enjoytrip/member/controller/AuthControllerTest.java
  src/test/java/enjoytrip/member/service/MemberServiceTest.java
Labels: enhancement
